- hosts: all
  become: true

  tasks:
    - name: "Installing Prerequisite packages"
      yum:
        name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'git']
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
        mode: 0644

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled

    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
        dest: /bin/docker-compose
        mode: 'a+x'

    - name: Allow user centos to manage Docker 
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Check if swap file exists
      stat:
        path: /swap
      register: swap_file_check

    - name: Add swap if required
      block:
        - name: Create swap file
          command: dd if=/dev/zero of=/swap bs=1M count=2048

        - name: Change swap file permissions
          file: path="/swap"
                owner=root
                group=root
                mode=0600
          when: not swap_file_check.stat.exists

        - name: Format swap file
          command: "mkswap /swap"
          when: not swap_file_check.stat.exists

        - name: Write swap entry in fstab
          mount: name=none
                src=/swap
                fstype=swap
                opts=sw
                passno=0
                dump=0
                state=present

        - name: Turn on swap
          command: swapon -a
      when: not swap_file_check.stat.exists